// State, District and crop Options for crop prediction
// stateDistrictData.js

export const state_arr = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const s_a = [
  "NICOBARS | NORTH AND MIDDLE ANDAMAN | SOUTH ANDAMANS",
  "ANANTAPUR | CHITTOOR | EAST GODAVARI | GUNTUR | KADAPA | KRISHNA | KURNOOL | PRAKASAM | SPSR NELLORE | SRIKAKULAM | VISAKHAPATANAM | VIZIANAGARAM | WEST GODAVARI",
  "ANJAW | CHANGLANG | DIBANG VALLEY | EAST KAMENG | EAST SIANG | KURUNG KUMEY | LOHIT | LONGDING | LOWER DIBANG VALLEY | LOWER SUBANSIRI | NAMSAI | PAPUM PARE | TAWANG | TIRAP | UPPER SIANG | UPPER SUBANSIRI | WEST KAMENG | WEST SIANG",
  "BAKSA | BARPETA | BONGAIGAON | CACHAR | CHIRANG | DARRANG | DHEMAJI | DHUBRI | DIBRUGARH | DIMA HASAO | GOALPARA | GOLAGHAT | HAILAKANDI | JORHAT | KAMRUP | KAMRUP METRO | KARBI ANGLONG | KARIMGANJ | KOKRAJHAR | LAKHIMPUR | MARIGAON | NAGAON | NALBARI | SIVASAGAR | SONITPUR | TINSUKIA | UDALGURI",
  "ARARIA | ARWAL | AURANGABAD | BANKA | BEGUSARAI | BHAGALPUR | BHOJPUR | BUXAR | DARBHANGA | GAYA | GOPALGANJ | JAMUI | JEHANABAD | KAIMUR (BHABUA) | KATIHAR | KHAGARIA | KISHANGANJ | LAKHISARAI | MADHEPURA | MADHUBANI | MUNGER | MUZAFFARPUR | NALANDA | NAWADA | PASHCHIM CHAMPARAN | PATNA | PURBI CHAMPARAN | PURNIA | ROHTAS | SAHARSA | SAMASTIPUR | SARAN | SHEIKHPURA | SHEOHAR | SITAMARHI | SIWAN | SUPAUL | VAISHALI",
  "CHANDIGARH",
  "BALOD | BALODA BAZAR | BALRAMPUR | BASTAR | BEMETARA | BIJAPUR | BILASPUR | DANTEWADA | DHAMTARI | DURG | GARIYABAND | JANJGIR-CHAMPA | JASHPUR | KABIRDHAM | KANKER | KONDAGAON | KORBA | KOREA | MAHASAMUND | MUNGELI | NARAYANPUR | RAIGARH | RAIPUR | RAJNANDGAON | SUKMA | SURAJPUR | SURGUJA",
  "DADRA AND NAGAR HAVELI",
  "NORTH GOA | SOUTH GOA",
  "AHMADABAD | AMRELI | ANAND | BANAS KANTHA | BHARUCH | BHAVNAGAR | DANG | DOHAD | GANDHINAGAR | JAMNAGAR | JUNAGADH | KACHCHH | KHEDA | MAHESANA | NARMADA | NAVSARI | PANCH MAHALS | PATAN | PORBANDAR | RAJKOT | SABAR KANTHA | SURAT | SURENDRANAGAR | TAPI | VADODARA | VALSAD",
  "AMBALA | BHIWANI | FARIDABAD | FATEHABAD | GURGAON | HISAR | JHAJJAR | JIND | KAITHAL | KARNAL | KURUKSHETRA | MAHENDRAGARH | MEWAT | PALWAL | PANCHKULA | PANIPAT | REWARI | ROHTAK | SIRSA | SONIPAT | YAMUNANAGAR",
  "BILASPUR | CHAMBA | HAMIRPUR | KANGRA | KINNAUR | KULLU | LAHUL AND SPITI | MANDI | SHIMLA | SIRMAUR | SOLAN | UNA",
  "ANANTNAG | BADGAM | BANDIPORA | BARAMULLA | DODA | GANDERBAL | JAMMU | KARGIL | KATHUA | KISHTWAR | KULGAM | KUPWARA | LEH LADAKH | POONCH | PULWAMA | RAJAURI | RAMBAN | REASI | SAMBA | SHOPIAN | SRINAGAR | UDHAMPUR",
  "BOKARO | CHATRA | DEOGHAR | DHANBAD | DUMKA | EAST SINGHBUM | GARHWA | GIRIDIH | GODDA | GUMLA | HAZARIBAGH | JAMTARA | KHUNTI | KODERMA | LATEHAR | LOHARDAGA | PAKUR | PALAMU | RAMGARH | RANCHI | SAHEBGANJ | SARAIKELA KHARSAWAN | SIMDEGA | WEST SINGHBHUM",
  "BAGALKOT | BANGALORE RURAL | BELGAUM | BELLARY | BENGALURU URBAN | BIDAR | BIJAPUR | CHAMARAJANAGAR | CHIKBALLAPUR | CHIKMAGALUR | CHITRADURGA | DAKSHIN KANNAD | DAVANGERE | DHARWAD | GADAG | GULBARGA | HASSAN | HAVERI | KODAGU | KOLAR | KOPPAL | MANDYA | MYSORE | RAICHUR | RAMANAGARA | SHIMOGA | TUMKUR | UDUPI | UTTAR KANNAD | YADGIR",
  "ALAPPUZHA | ERNAKULAM | IDUKKI | KANNUR | KASARAGOD | KOLLAM | KOTTAYAM | KOZHIKODE | MALAPPURAM | PALAKKAD | PATHANAMTHITTA | THIRUVANANTHAPURAM | THRISSUR | WAYANAD",
  "AGAR MALWA | ALIRAJPUR | ANUPPUR | ASHOKNAGAR | BALAGHAT | BARWANI | BETUL | BHIND | BHOPAL | BURHANPUR | CHHATARPUR | CHHINDWARA | DAMOH | DATIA | DEWAS | DHAR | DINDORI | GUNA | GWALIOR | HARDA | HOSHANGABAD | INDORE | JABALPUR | JHABUA | KATNI | KHANDWA | KHARGONE | MANDLA | MANDSAUR | MORENA | NARSINGHPUR | NEEMUCH | PANNA | RAISEN | RAJGARH | RATLAM | REWA | SAGAR | SATNA | SEHORE | SEONI | SHAHDOL | SHAJAPUR | SHEOPUR | SHIVPURI | SIDHI | SINGRAULI | TIKAMGARH | UJJAIN | UMARIA | VIDISHA",
  "AHMEDNAGAR | AKOLA | AMRAVATI | AURANGABAD | BEED | BHANDARA | BULDHANA | CHANDRAPUR | DHULE | GADCHIROLI | GONDIA | HINGOLI | JALGAON | JALNA | KOLHAPUR | LATUR | MUMBAI | NAGPUR | NANDED | NANDURBAR | NASHIK | OSMANABAD | PALGHAR | PARBHANI | PUNE | RAIGAD | RATNAGIRI | SANGLI | SATARA | SINDHUDURG | SOLAPUR | THANE | WARDHA | WASHIM | YAVATMAL",
  "BISHNUPUR | CHANDEL | CHURACHANDPUR | IMPHAL EAST | SENAPATI | TAMENGLONG | THOUBAL | UKHRUL",
  "EAST GARO HILLS | EAST JAINTIA HILLS | EAST KHASI HILLS | NORTH GARO HILLS | RI BHOI | SOUTH GARO HILLS | SOUTH WEST GARO HILLS | SOUTH WEST KHASI HILLS | WEST GARO HILLS | WEST KHASI HILLS",
  "AIZAWL | CHAMPHAI | KHAWZAWL | LAWNGTLAI | LUNGLEI | MAMIT | SERCHHIP | THENSANG | TUILAHL",
  "DIMAPUR | KIPHIRE | KOHIMA | LONGLENG | MON | PHEK | TUENSANG | WOKHA | ZUNHEBOTO",
  "BALASORE | BALESHWAR | BHADRAK | BOUDH | CUTTACK | DHENKANAL | GANJAM | GAJAPATI | JAGATSINGHAPUR | JHARSUGUDA | KALAHANDI | KANDHAMAL | KENDRAPARA | KENDUJHAR | KHURDA | NAYAGADH | NUAPADA | RAYAGADA | SAMBALPUR | SONEPUR | SUBARNAPUR | DEOGARH",
  "KARAIKAL | MAHE | PUDUCHERRY | YANAM",
  "AMRITSAR | BARNALA | BATALA | FARIDKOT | FATEHGARH SAHIB | FEROZEPUR | GURDASPUR | HOSHIARPUR | JALANDHAR | KAPURTHALA | LUDHIANA | MANSA | MOGA | PATHANKOT | PATIALA | ROPAR | SANGRUR | SHAHDI | SRI MUKTSAR SAHIB | TARANTARAN",
  "JAIPUR | AJMER | ALWAR | BANSWARA | BARAN | BARMER | BHARATPUR | BIKANER | BOSE | CHITTORGARH | DHOLPUR | DUNGARPUR | HANUMANGARH | JHUNJHUNU | JODHPUR | KARAULI | KOTA | NAGAUR | PALI | RAJSAMAND | SAWAI MADHOPUR | SIKAR | TONK | UDAIPUR",
  "EAST SIKKIM | NORTH SIKKIM | SOUTH SIKKIM | WEST SIKKIM",
  "CHENGALPATTU | COIMBATORE | CUDDALORE | DHARMAPURI | DINDIGUL | ERODE | KANNIYAKUMARI | KARUR | MADURAI | NAGAPATTINAM | NAMAKKAL | PERAMBALUR | PUDUKKOTTAI | RAMANATHAPURAM | SALEM | SIVAGANGA | TIRUCHIRAPALLI | TIRUNELVELI | TIRUPPUR | TIRUVALLUR | TIRUVANNAMALAI | VELLORE | VIRDACHALAI",
  "ADILABAD | BHADRADRI KOTHAGUDEM | BANGALORE | BANSWARA | BHADRADRI KOTHAGUDEM | WARANGAL RURAL | WARANGAL URBAN",
  "AMJORE | AGARTALA | BILASHPUR | DHARMANAGAR | KAILASHAHAR | KHOWAI | LAWNGTLAI | MAMIT | NORTH TRIPURA | SOUTH TRIPURA | WEST TRIPURA",
  "AGRA | ALIGARH | ALLAHABAD | AMETHI | AMROHA | AURAIYA | AYODHYA | BADAUN | BAHRAICH | BALLIA | BANDA | BARABANKI | BAREILLY | BASTI | BHIWANI | BIJNOR | BULANDSHAHR | CHANDAULI | CHITRAKOOT | DEORIA | ETAAH | ETAWAH | FAIZABAD | FARRUKHABAD | FATEHPUR | GAZA | GORAKHPUR | HAMIRPUR | HAPUR | HARDOI | JALAUN | JAUNPUR | JHANSI | KANPUR DEHAT | KANPUR NAGAR | KASGANJ | KAUSHAMBI | KUSHINAGAR | LAKHIMPUR KHERI | LALITPUR | MAHARAJGANJ | MAU | MEERUT | MIRZAPUR | MORADABAD | MUZAFFARNAGAR | PILIBHIT | RAEBARELI | RAMPUR | RAYABARELI | SHAHJAHANPUR | SHEIKHPUR | SIDDHARTHNAGAR | SITAPUR | SONBHADRA | UNNAO | VARANASI",
  "ALMORA | BAGESHWAR | BALESHWAR | CHAMOLI | CHAMPawat | HARIDWAR | NAINITAL | PITHORAGARH | RUDRAPRYAG | TEHRI GARHWAL | US NAGAR | UTTARKASHI",
  "BIRBHUM | BANKURA | BARDHAMAN | COOCHBEHAR | DARJEELING | DAKSHIN DINAJPUR | HOOGHLY | HOWRAH | JALPAIGURI | JHARGRAM | KALIMPONG | MALDAH | MURSHIDABAD | NADIA | NORTH 24 PARGANAS | PURULIA | SOUTH 24 PARGANAS | PASCHIM MEDINIPUR | PURBA MEDINIPUR",
];

function print_state(state_id) {
  // given the id of the <select> tag as function argument, it inserts <option> tags
  var option_str = document.getElementById(state_id);
  option_str.length = 0;
  option_str.options[0] = new Option("Select State", "");
  option_str.selectedIndex = 0;
  for (var i = 0; i < state_arr.length; i++) {
    option_str.options[option_str.length] = new Option(
      state_arr[i],
      state_arr[i]
    );
  }
}

function print_city(city_id, city_index) {
  var option_str = document.getElementById(city_id);
  option_str.length = 0; // Fixed by Julian Woods
  option_str.options[0] = new Option("Select District", "");
  option_str.selectedIndex = 0;
  var city_arr = s_a[city_index].split("|");
  for (var i = 0; i < city_arr.length; i++) {
    option_str.options[option_str.length] = new Option(
      city_arr[i],
      city_arr[i]
    );
  }
}

// dropdown for rainfall prediction

var months = [
  "ANNUAL",
  "JAN",
  "FEB",
  "MAR",
  "APR",
  "MAY",
  "JUN",
  "JUL",
  "AUG",
  "SEP",
  "OCT",
  "NOV",
  "DEC",
  "Jan-Feb",
  "Mar-May",
  "Jun-Sep",
  "Oct-Dec",
];

function print_months(month_id) {
  var option_months = document.getElementById(month_id);
  option_months.length = 0;
  option_months.options[0] = new Option("Select Month", "");
  option_months.selectedIndex = 0;
  for (var i = 0; i < months.length; i++) {
    option_months.options[option_months.length] = new Option(
      months[i],
      months[i]
    );
  }
}

var region = [
  "ANDAMAN & NICOBAR ISLANDS",
  "ARUNACHAL PRADESH",
  "ASSAM & MEGHALAYA",
  "NAGA MANI MIZO TRIPURA",
  "SUB HIMALAYAN WEST BENGAL & SIKKIM",
  "GANGETIC WEST BENGAL",
  "ORISSA",
  "JHARKHAND",
  "BIHAR",
  "EAST UTTAR PRADESH",
  "WEST UTTAR PRADESH",
  "UTTARAKHAND",
  "HARYANA DELHI & CHANDIGARH",
  "PUNJAB",
  "HIMACHAL PRADESH",
  "JAMMU & KASHMIR",
  "WEST RAJASTHAN",
  "EAST RAJASTHAN",
  "WEST MADHYA PRADESH",
  "EAST MADHYA PRADESH",
  "GUJARAT REGION",
  "SAURASHTRA & KUTCH",
  "KONKAN & GOA",
  "MADHYA MAHARASHTRA",
  "MATATHWADA",
  "VIDARBHA",
  "CHHATTISGARH",
  "COASTAL ANDHRA PRADESH",
  "TELANGANA",
  "RAYALSEEMA",
  "TAMIL NADU",
  "COASTAL KARNATAKA",
  "NORTH INTERIOR KARNATAKA",
  "SOUTH INTERIOR KARNATAKA",
  "KERALA",
  "LAKSHADWEEP",
];

function print_region(region_id) {
  var option_region = document.getElementById(region_id);
  option_region.length = 0;
  option_region.options[0] = new Option("Select Region", "");
  option_region.selectedIndex = 0;
  for (var i = 0; i < region.length; i++) {
    option_region.options[option_region.length] = new Option(
      region[i],
      region[i]
    );
  }
}
